import { OnboardingRecord } from "../types/onboarding";

export const SEED_ONBOARDINGS: OnboardingRecord[] = [
  {
    employee_id: "HR-TEST-1001",
    name: "Alex Morgan",
    department: "Engineering",
    start_date: "2026-04-01",
    role: "Platform Engineer",
    checklist: ["Security Background Check", "Laptop Provisioning", "System Access"],
    status: "PENDING",
    notes: "Awaiting hardware provisioning and system setup.",
    created_at: "2026-03-25T08:00:00Z",
    updated_at: "2026-03-25T08:00:00Z",
  },
  {
    employee_id: "EMP-091",
    name: "Alex Chen",
    department: "Core Engineering",
    start_date: "2026-04-01",
    role: "Senior Software Engineer",
    checklist: ["Security Background Check", "Laptop Provisioning", "GitHub & Cloud Access"],
    status: "PENDING",
    notes: "Candidate starting April 2026.",
    created_at: "2026-03-20T10:00:00Z",
    updated_at: "2026-03-20T10:00:00Z",
  },
  {
    employee_id: "HR-TEST-1002",
    name: "Jordan Lee",
    department: "Product",
    start_date: "2026-04-10",
    role: "Product Manager",
    checklist: ["Security Background Check", "Welcome Session Scheduled"],
    status: "PENDING",
    notes: "Direct report to VP Product.",
    created_at: "2026-03-22T09:30:00Z",
    updated_at: "2026-03-22T09:30:00Z",
  },
  {
    employee_id: "HR-TEST-1003",
    name: "Taylor Swift",
    department: "Design",
    start_date: "2026-03-15",
    role: "Lead UI Designer",
    checklist: ["Security Background Check", "Figma Licenses", "Laptop Provisioning", "Benefits Enrolled"],
    status: "COMPLETED",
    notes: "All onboarding steps completed successfully.",
    created_at: "2026-03-10T11:00:00Z",
    updated_at: "2026-03-15T16:00:00Z",
  },
];
